version: "3.9"

services:
  web:
    container_name: apollo_user_access_api
    build:
      context: ./src/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

networks:
  internal:
