version: "3.9"

services:
  web:
    container_name: apollo_user_access_api
    build:
      context: ./src/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_access_api.rule=Host(`useraccess.${HOST}`)"
      - "traefik.http.routers.user_access_api.tls=true"
      - "traefik.http.routers.user_access_api.entrypoints=http,https"
    networks:
      - apollo

networks:
  apollo:
    external: true