api:
  ingress:
    configured: false
    rewritePath: true
    pathPrefix: ""

  service:
    type: LoadBalancer
    port: 80
  
  deployment:
    replicaCount: 1
    container:
      image:
        repository: eu.gcr.io/dddlegion-apollo/user-access
        pullPolicy: IfNotPresent
        tag: ""
      port: 80
  
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  
  resources: {}
  
  tolerations: []
  
  affinity: {}
