api:
  ingress:
    configured: false
    rewritePath: true
    pathPrefix: ""

  service:
    type: LoadBalancer
    port: 80
  
  route:
    enabled: true
    name: useraccess-api-route
    gatewayName: apollo-api-gateway
    hostnames:
      - "apollo.dddlegion.tech"
    paths:
      - path: /
  
  deployment:
    replicaCount: 1
    container:
      image:
        repository: eu.gcr.io/dddlegion-apollo/user-access
        pullPolicy: IfNotPresent
        tag: ""
      port: 80
    resources: { }
    tolerations: [ ]
    affinity: { }
  
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
