version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Testing the application
          command: |
            make ci-tests
  
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t apollo-user-access:circleci ./src/
            docker images
  
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build Docker image
          command: |
            docker build -t apollo-user-access:circleci ./src/
            docker images
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push apollo-user-access:circleci -a $HEROKU_APP_NAME
            heroku container:release apollo-user-access:circleci -a $HEROKU_APP_NAME
      
workflows:
  main:
    jobs:
      - test
      - hold:
          requires:
            - test
          type: approval
      - build:
          requires:
            - hold
      - deploy:
          requires:
            - build
