version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.0
  gcp-cli: circleci/gcp-cli@2.4.0
  gcr: circleci/gcp-gcr@0.15.0
  helm: circleci/helm@1.2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: $CI_API_IMAGE
          tag: $CIRCLE_WORKFLOW_ID-$CIRCLE_SHA1
          path: ./src
          docker-context: ./src
          registry-url: eu.gcr.io
      - gcr/push-image:
          image: $CI_API_IMAGE
          tag: $CIRCLE_WORKFLOW_ID-$CIRCLE_SHA1
          registry-url: eu.gcr.io
  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Testing the application
          command: |
            make ci-tests
  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - kubernetes/install-kubectl
      - gcp-cli/initialize
      - helm/install-helm-client:
          version: v3.7.0
      - run:
          name: Upgrade helm chart
          command: |
            make ci-deploy

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          requires:
            - test
          type: approval
      - deploy:
          requires:
            - hold
