version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@1.4.0
  gcr: circleci/gcp-gcr@0.15.0
  helm: circleci/helm@1.2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: dddlegion-apollo/user-access # possibly move to env variable
          tag: $CIRCLE_WORKFLOW_ID-$CIRCLE_SHA1
          docker-context: ./src/
          registry-url: eu.gcr.io
      - gcr/push-image:
          image: dddlegion-apollo/user-access # possibly move to env variable
          tag: $CIRCLE_WORKFLOW_ID-$CIRCLE_SHA1
          registry-url: eu.gcr.io
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Testing the application
          command: |
            make ci-tests
  deploy:
    machine: true
    steps:
      - gcp-gke/install
      - run:
          name: Upgrade helm chart
          command: |
            make ci-deploy

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          requires:
            - test
          type: approval
      - deploy:
          requires:
            - hold
