{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ $svcPort }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute